# ($s) - seconds
# ($p) - bot prefix
# ($t) - time left to wait
# ($tnum) - ticket number


onReady = "готов к работе"
gameActivity = "($p)help - список команд"
commandOnCooldown = "Подождите **__($s)__**с. перед тем как использовать команду еще раз."
commandNotFound = "Команда не распознана. Используйте **__($p)help__** или проверьте синтаксис."


h_helpTitle = "**Список общедоступных команд:**"
h_ticketInvite = "Пригласить в тикет №t всех упомянутых участников."
h_help = "Показать список общедоступных команд."

h_helpAdminTitle = "**Список команд для админов:**"
h_ticketButton = "Отправить в канал #channel сообщение с кнопкой для создания тикетов, с текстом из прошлого сообщения в чате."
h_ticketText = "Поменять стандартный текст при создании нового тикета на текст из прошлого сообщения."
h_ticketCooldown = "Поменять кулдаун на создание новых тикетов."
h_ticketReset = "Обнулить кулдаун создания тикетов для конкретного(-ых) пользователя(-ей)."
h_setLogsChannel = "Установить или удалить (None) канал для логирования закрытых/удаленных тикетов."
h_helpAdm = "Показать список команд для админов."


hour = "ч."
minute = "мин."
second = "сек."
createTicket = "Создать тикет"
ticketCooldownTitle = "Вы создаете тикеты слишком часто!"
ticketCooldownDescription = "Подождите ($t) или напишите администратору."
ticket = "Тикет"
newTicketIsNowOpen = "Тикет №($tnum) открыт."
newTicketIsNowClosed = "Тикет №($tnum) закрыт."
ticketIsNowDeleted = "Тикет №($tnum) удален."
ticketIsNowOpen = "Тикет снова открыт."
ticketIsNowClosedTitle = "Тикет закрыт."
ticketIsNowClosedDescription = "Он все еще доступен для просмотра, но без возможности отправки сообщений.\nАдминистрация может удалить тикет в закрепленном сообщении."
closeTicket = "Закрыть тикет"
openTicket = "Открыть тикет"
deleteTicket = "Удалить тикет"
joinTheTicket = "Присоединиться"
refuse = "Отказаться"
oops = "Упс..."
ticketNoLongerExist = "Похоже, что этот тикет больше не существует."
alreadyJoined = "Вы уже присоединились."
ticketIsClosedTitle = "Этот тикет закрыт."
ticketIsClosedDescription = "Чтобы присоединиться - попросите администрацию его открыть."
ticketIsNowAvailable = "Теперь вам доступен канал тикета №($tnum)."
userHasJoined = "Пользователь присоединился к тикету."
userRefusedToJoin = "Пользователь отказался присоединяться к тикету."
textHasBeenChanged = "Текст успешно изменен."
somethingsWrong = "Что-то не так..."
incorrectTicketNumber = "Вы ввели неправильный номер тикета или этот тикет открыт не вами.\nПример исползования команды: `%ti 34 @user1 @user2`"
uInvitedToTicketTitle = "Вы были приглашены в тикет №($tnum)"
uInvitedToTicketDescription = "Если вы хотите к нему присоединиться - нажмите на соответсвующую кнопку под этим сообщением:"
cooldownChanged = "Кулдаун успешно изменен."
cooldownReset = "Куладун успешно сброшен."
setLogsWrongChannel = "Канал указан неверно."
setLogsNone = "Логи отключены."
setLogsSuccess = "Канал для логов обновлен."
